#! /bin/sh

sxhkd &

# bspc monitor DisplayPort-1 -d I II III IV V VI VII VIII
bspc monitor DisplayPort-0 -d I II III IV
bspc monitor DisplayPort-1 -d V VI VII VIII

bspc config border_width         2
bspc config window_gap          24

bspc config single_monocle true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
